# Generated by Django 5.2.13 on 2026-04-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_completed_task_is_deleted_task_created_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['is_deleted', 'updated_at'], name='tasks_task_is_dele_a05af0_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'updated_at'], name='tasks_task_status_2dc0fe_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority', 'updated_at'], name='tasks_task_priorit_018456_idx'),
        ),
    ]
